#!/bin/bash

# pip install w1thermsensor

git clone https://github.com/timofurrer/w1thermsensor.git && cd w1thermsensor
sudo python setup.py install

#due to pirateship image deficiencies
echo 'w1-gpio' >> /etc/modules
echo 'w1-therm' >> /etc/modules
